--Even Fibonacci numbers
--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci :: Int -> Int
fibonacci 1 = 1
fibonacci 2 = 2
fibonacci x = fibonacci (x-1) + fibonacci (x-2)

fibs = takeWhile (<4000000) [x | x <- map fibonacci [1..], even x] 
a = sum fibs